[package]
name = "pxdct-py"
version = "0.3.3"
edition = "2024"
readme = "README.md"
keywords = ["dct", "discrete", "fourier"]
license = "BSD-3-Clause OR Apache-2.0"
authors = ["Radzivon Bartoshyk"]
documentation = "https://github.com/awxkee/pxdct"
categories = ["algorithms", "science"]
homepage = "https://github.com/awxkee/pxdct"
repository = "https://github.com/awxkee/pxdct"
exclude = ["*.jpg", "/assets", "*.png", "*.sh", "/assets/*"]
rust-version = "1.89.0"

[dependencies]
pxdct = { path = "../" }
pyo3 = { version = "0.28.2", features = ["extension-module"] }
numpy = "0.28.0"

[features]
default = ["avx", "neon"]
avx = ["pxdct/avx"]
neon = ["pxdct/neon"]
fcma = ["pxdct/fcma"]