[package]
name = "pxdct-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
arbitrary = { version = "1.4.2", features = ["derive"] }

[dependencies.pxdct]
path = ".."
default-features = false

[[bin]]
name = "dct"
path = "dct/dct.rs"
test = false
doc = false
bench = false

[[bin]]
name = "dct4"
path = "dct4/dct4.rs"
test = false
doc = false
bench = false

[[bin]]
name = "dct2_f64"
path = "dct2_f64/dct2_f64.rs"
test = false
doc = false
bench = false

[[bin]]
name = "dct4_f64"
path = "dct4_f64/dct4_f64.rs"
test = false
doc = false
bench = false

[[bin]]
name = "type1"
path = "type1/type1.rs"
test = false
doc = false
bench = false

[features]
default = []
avx = ["pxdct/avx"]
neon = ["pxdct/neon"]
fcma = ["pxdct/fcma"]