[package]
name = "app"
version = "0.1.0"
edition = "2024"

[dependencies]
criterion = "0.8.1"
pxdct = {path = ".."}
rand = "0.10.1"
num-complex = "0.4.6"
pxfm = "0.1.27"
primal-check = "0.3.4"
regex = "1.12.2"
rustdct = "0.7.1"
zaft = { version = "0.3.8", features = ["fcma"] }
ndarray = "0.17.2"

[[bench]]
name = "dct2"
harness = false

[[bench]]
name = "dct3"
harness = false

[[bench]]
name = "dct4"
harness = false